# Generated by Django 3.1.6 on 2021-06-01 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoOrganicosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(verbose_name='Fecha de compra')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('direccion_entrega', models.CharField(max_length=400)),
                ('metodo_pago', models.CharField(max_length=200)),
                ('numero_tarjeta', models.CharField(max_length=200)),
                ('numero_cuota', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadoOrganicosApp.carrito')),
            ],
            options={
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
