# Generated by Django 3.1.6 on 2021-05-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoOrganicosApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
