# Generated by Django 3.1.6 on 2021-06-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoOrganicosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='precio_total',
            field=models.FloatField(default=0),
        ),
    ]
